#!/usr/bin/python
# -*- coding: utf8 -*-
'''Skarlis Thrasyvoulos,P15127'''



import json, requests
from imdb import IMDb
import omdb
import imdb
import urllib
from jabbapylib.web.web import get_page


BASE = 'http://www.omdbapi.com/?i=&'


class Movie(object):

    def __init__(self, keyword):
        self.keyword = keyword
        self.url = BASE + urllib.urlencode({'t' : keyword})
        self.d = self.get_info()


    def get_info(self):
        text = get_page(self.url)
        return json.loads(text)

    def __getitem__(self, key):
        return self.d[key]

    def __str__(self):
        li = []
        for key in self.d:
            li.append("{key}: {value}".format(key=key, value=self.d[key]))

        return '\n'.join(li)


def get_rating(title):
    m = Movie(title)

    return float(m['imdbRating'])


if __name__ == "__main__":

    m = Movie(raw_input('Enter movie title: '))
    while m['Response']=='False':
        m = Movie(raw_input('Please, re-enter movie title:'))

print 'Title: {title}'.format(title=m['Title'])
print 'Year: {year}'.format(year=m['Year'])
print 'Rating: {rating}'.format(rating=m['imdbRating'])
print 'Awards: {awards}'.format(awards=m['Awards'])

